[build]
  command = "npm run build"
  publish = "dist/zamn/browser"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

[[plugins]]
  package = "@netlify/plugin-angular-runtime"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/angular-ssr"
  status = 200
  force = true 